version: "3"
services:
  db:
    image: "mdillon/postgis:9.6"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  back-end:
    build: ./back-end
    container_name: back-end
    ports:
      - 8080:3000
    links:
      - db
    env_file:
      - ./back-end/.env
  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - 3000:3000
    links:
      - back-end
    restart: unless-stopped
    ports:
      - 1234:1234
    links:
      - back-end
    tty: true
    stdin_open: true