version: "3"
services:
  db:
    image: "mdillon/postgis:9.6"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  back-end:
    build: ./back-end
    volumes:
      - ./back-end/:/app
    ports:
      - 8080:3000
    env_file:
      - ./back-end/.env
    links:
      - db
    command: ["npm", "run", "dev"]
  front-end:
    build: ./front-end
    restart: unless-stopped
    ports:
      - 1234:1234
    volumes:
      - ./front-end:/usr/src/app
      - /app/node_modules
    links:
      - back-end
    command: npm start
    tty: true
    stdin_open: true
